name: Tests

on:
  push:
    branches:
      - "main"
    tags:
      - v*
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Check out code
        uses: actions/checkout@v2
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test -race ./...
      - name: Build
        run: go build -v ./cmd/toggl_exporter
